stages:
  - setup
  - test
################################
# Template for all build steps
################################
.build_template:
  before_script:
    - pwd
    - ls
    - python -V
    - pip -V
  script:
    - echo "Base Job Script. This should be not be seen"

################
# Setup Step
################
setup_env:
  extends:
    - .build_template
  stage: setup
  tags:
    - python
    - windows
    - shell
    - GPU
  script:
    - pip install virtualenv
    - virtualenv venv
    - venv/Scripts/activate.ps1
    - pip install -e .
    - pip install -r requirements_dev.txt
    - pip install -r requirements_gpu.txt
    - pip lists

#################
# GPU Test Build
#################

run_pytest:
  extends:
    - .build_template
  stage: test
  script:
    - venv/Scripts/activate.ps1
    - pytest