stages:
  - setup
  - test
################################
# Template for all build steps
################################
.build_template:
  before_script:
    - pwd
    - ls | Format-Table LastWriteTime,Length,Name
    - python -V
    - pip -V
  script:
    - echo "Base Job Script. This should be not be seen"


################
# Setup Step
################
setup_env:
  extends:
    - .build_template
  stage: setup
  tags:
    - python
    - windows
    - shell
    - GPU
  script:
    - pip install virtualenv
    - virtualenv venv
    - venv/Scripts/activate.ps1
    - pip install -e .
    - pip install -r requirements_dev.txt
    - pip install -r requirements_gpu.txt
    - pip list
  artifacts:
    paths:
      - venv
      # THis is needed apparently for ivadomed script to work. 
      - ivadomed.egg-info

#################
# GPU Test Build
#################

run_pytest:
  extends:
    - .build_template
  stage: test
  tags:
    - python
    - windows
    - shell
    - GPU
  script:
    # Activate VENV
    - venv/Scripts/activate.ps1
    # Check Torch CUDA availability, Torch version
    - python -c "import torch; print(torch.cuda.is_available()); print(torch.__version__)"
    # Run Full PyTest with GPU
    - pytest