stages:
  - setup
  - test

.build_template:
  before_script:
    - pwd
    - ls
    - get-command python
    - get-command pip
    - python -V
    - pip -V
  tags:
    - python
    - windows
    - shell
    - GPU
  script:
    - echo "Base Job Script. This should be not be seen"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'

setup_env:
  stage: setup
  script:
    - pip install virtualenv
    - virtualenv venv
    - venv/Scripts/activate.ps1
    - pip install -e .
    - pip install -r requirements_dev.txt
    - pip install -r requirements_gpu.txt

run_pytest:
  stage: test
  script:
    - venv/Scripts/activate.ps1
    - pytest